version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo ///////////////// Construct building runtime for nodejs  /////////////////
  pre_build:
    commands:
      - echo ///////////////// Start to compile resources... /////////////////
      - npm install
  build:
    commands:
      - echo ///////////////// Build started on `date` /////////////////
      - ./node_modules/.bin/ng build --prod
  post_build:
    commands:
      - echo ///////////////// Build completed on `date` /////////////////
      - aws s3 sync dist s3://parallel-web --delete
artifacts:
  files:
    - dist/*